### ISSUE TITLE
Switch to MoreObjects for Guava ToString

### ISSUE THREAD

**Issue by jrduncans** [mjedynak/EqualsHashCodeDeluxeGenerator#18]
In Guava 18.0 Objects.toStringHelper is deprecated, and moved to MoreObjects.toStringHelper.  An option to support Guava 18.0 & higher would be nice.

**Comment by paolofulgoni** [comment]
Where is `Objects.toStringHelper` used?

**Comment by jrduncans** [comment]
Ah, right, that's rather embarrassing.  That's the built-in ToString functionality.  Was obviously exploring both toString & equals/hashCode generation the same day and got myself confused.
