### ISSUE TITLE
Speed comparsion of hashCode method generated by plugin and directly by IntelliJ

### ISSUE THREAD

**Issue by arnostv** [mjedynak/EqualsHashCodeDeluxeGenerator#2]
Program at

https://github.com/arnostv/archery/tree/master/src/me/arnost/hashcode

shows that hashCode method generated by this plugin are little bit slower than hashCode generated directly by IntelliJ IDEA

**Comment by paolofulgoni** [comment]
IMHO this is not an issue of the plugin

**Comment by electrum** [comment]
FYI, benchmarks like that are notoriously unreliable for a number of non-obvious reasons. Use JMH for accurate JVM benchmarks: http://openjdk.java.net/projects/code-tools/jmh/

**Comment by electrum** [comment]
Watch this excellent talk by the author of JMH to learn more: http://medianetwork.oracle.com/video/player/2630310904001
